version: '3.8'

services:
    mysql:
        container_name: pji_mysql
        image: mysql
        restart: unless-stopped

        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASS}

        ports:
            - '${DB_PORT}:${DB_PORT}'
        volumes:
            - P2P-discussion-app:/var/lib/mysql

    api:
        container_name: pji_app
        # dont restart the container if it fails
        restart: no
        depends_on:
            - mysql

        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            PORT: ${PORT}
            NODE_ENV: ${NODE_ENV}

        build:
            dockerfile: Dockerfile
            context: .

        volumes:
            - .:/app
        ports:
            - '${PORT}:${PORT}'

volumes:
    P2P-discussion-app:
